### ISSUE TITLE
jobstats and Grafana 

### ISSUE THREAD

**Issue by mikygit** [PrincetonUniversity/jobstats#11]
Hello,
 Would it be possible to get a step by step documentation for installing and make grafana works with jobstats.
 The current one is rather ... cryptic ... to me at least ;-)
Thx.

**Comment by plazonic** [comment]
Hello,

first of all sorry for not replying sooner, busy with lots of other projects before summer vacation :).

Back to issue at hand, yes, sorry, we did assume a working Grafana setup into one could just import the dashboard and then tweak what's needed. Also because we are not the best people to provide more than that (I am hardly a grafana expert) but I can try.

What I'd recommend is to start by installing it and then adding the [prometheus data source](https://grafana.com/docs/grafana/latest/datasources/prometheus/configure-prometheus-data-source/). Next I would not start with our dashboard but instead try one of the node exporter dashboards first - [maybe](https://grafana.com/grafana/dashboards/1860-node-exporter-full/). This data should already be in your prometheus so it pretty much should work - as long as you point it at the correct datasource at import time.

If that works try importing ours. You may have to edit it and then edit individual panels and change their datasource to yours.

**Comment by plazonic** [comment]
Any luck with grafana?

**Comment by mikygit** [comment]
Yes sorry for not responding sooner.
It works like a charm thank you again!
